apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: calc-add-app
  namespace: default
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: calc-add-app
  targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: calc-multi-app
  namespace: default
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: calc-multi-app
  targetCPUUtilizationPercentage: 50