apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-front-app
  labels:
    app: front-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - name: front-app
        image: antikuz/calc-front-app:latest
        ports:
        - containerPort: 80