apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-multi-app
  labels:
    app: add-multi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-app
  template:
    metadata:
      labels:
        app: multi-app
    spec:
      containers:
      - name: multi-app
        image: antikuz/calc-multi-app:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m